apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xqf0a5id8-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:324ec84744ea1410d137195701a321aa607c3af9@sha256:08fd2e1c5e211c2b98a09bb87d2f8a9d47bdd791f4206f3acceab1fb5982c00e
          name: container-image
