apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xqf0a5id8-nodejs
  janus-idp.io/tekton: xqf0a5id8-nodejs
  backstage.io/kubernetes-id: xqf0a5id8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xqf0a5id8-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
